language: scala

scala:
  - "2.10.6"
  - "2.11.8"
  - "2.12.1"

jdk:
  - oraclejdk8
  - oraclejdk7

node_js:
  - "6"

matrix:
  exclude:
  - scala: "2.12.1" 
    jdk: oraclejdk7

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
